// Code generated by protoc-gen-go.
// source: union2.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	union2.proto

It has these top-level messages:
	Foobar
	Baz
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Foobar struct {
	Type uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Foo  string `protobuf:"bytes,2,opt,name=foo" json:"foo,omitempty"`
	Bar  uint32 `protobuf:"varint,3,opt,name=bar" json:"bar,omitempty"`
}

func (m *Foobar) Reset()                    { *m = Foobar{} }
func (m *Foobar) String() string            { return proto.CompactTextString(m) }
func (*Foobar) ProtoMessage()               {}
func (*Foobar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Foobar) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Foobar) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func (m *Foobar) GetBar() uint32 {
	if m != nil {
		return m.Bar
	}
	return 0
}

type Baz struct {
	Type uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Baz  bool   `protobuf:"varint,2,opt,name=baz" json:"baz,omitempty"`
}

func (m *Baz) Reset()                    { *m = Baz{} }
func (m *Baz) String() string            { return proto.CompactTextString(m) }
func (*Baz) ProtoMessage()               {}
func (*Baz) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Baz) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Baz) GetBaz() bool {
	if m != nil {
		return m.Baz
	}
	return false
}

func init() {
	proto.RegisterType((*Foobar)(nil), "main.Foobar")
	proto.RegisterType((*Baz)(nil), "main.Baz")
}

func init() { proto.RegisterFile("union2.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xcd, 0xcb, 0xcc,
	0xcf, 0x33, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x72,
	0xe0, 0x62, 0x73, 0xcb, 0xcf, 0x4f, 0x4a, 0x2c, 0x12, 0x12, 0xe2, 0x62, 0x29, 0xa9, 0x2c, 0x48,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d, 0x02, 0xb3, 0x85, 0x04, 0xb8, 0x98, 0xd3, 0xf2, 0xf3,
	0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x90, 0x48, 0x52, 0x62, 0x91, 0x04, 0x33,
	0x58, 0x11, 0x88, 0xa9, 0xa4, 0xcd, 0xc5, 0xec, 0x94, 0x58, 0x85, 0x4b, 0x7b, 0x52, 0x62, 0x15,
	0x58, 0x3b, 0x07, 0x48, 0x71, 0x55, 0x12, 0x1b, 0xd8, 0x6e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xde, 0x29, 0xcd, 0x45, 0x8b, 0x00, 0x00, 0x00,
}
