// Code generated by protoc-gen-go.
// source: union.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	union.proto

It has these top-level messages:
	Foo
	Bar
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Foo struct {
	Type uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Foo  string `protobuf:"bytes,2,opt,name=foo" json:"foo,omitempty"`
}

func (m *Foo) Reset()                    { *m = Foo{} }
func (m *Foo) String() string            { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()               {}
func (*Foo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Foo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Foo) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

type Bar struct {
	Type uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Bar  uint32 `protobuf:"varint,2,opt,name=bar" json:"bar,omitempty"`
}

func (m *Bar) Reset()                    { *m = Bar{} }
func (m *Bar) String() string            { return proto.CompactTextString(m) }
func (*Bar) ProtoMessage()               {}
func (*Bar) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Bar) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Bar) GetBar() uint32 {
	if m != nil {
		return m.Bar
	}
	return 0
}

func init() {
	proto.RegisterType((*Foo)(nil), "main.Foo")
	proto.RegisterType((*Bar)(nil), "main.Bar")
}

func init() { proto.RegisterFile("union.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xcd, 0xcb, 0xcc,
	0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xd2, 0xe6,
	0x62, 0x76, 0xcb, 0xcf, 0x17, 0x12, 0xe2, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0d, 0x02, 0xb3, 0x85, 0x04, 0xb8, 0x98, 0xd3, 0xf2, 0xf3, 0x25, 0x98, 0x14, 0x18,
	0x35, 0x38, 0x83, 0x40, 0x4c, 0x90, 0x62, 0xa7, 0xc4, 0x22, 0x5c, 0x8a, 0x93, 0x12, 0x8b, 0xc0,
	0x8a, 0x79, 0x83, 0x40, 0xcc, 0x24, 0x36, 0xb0, 0x35, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x3d, 0x0f, 0xf0, 0x29, 0x75, 0x00, 0x00, 0x00,
}
